let baseUrl = 'http://localhost:3001';

export const rutasBack = {
    sucursales: {
        getSucursales: `${baseUrl}/sucursales/all`,
        getSucursalesByEmpresa: `${baseUrl}/sucursales/empresa`,
        postSucursal: `${baseUrl}/sucursales`,
        putSucursal: `${baseUrl}/sucursales`,
        patchSucursal: `${baseUrl}/sucursales`,
        deleteSucursal: `${baseUrl}/sucursales`,
        getSucursalPorId: `${baseUrl}/sucursales`,
        patchSucursalesStatus: `${baseUrl}/sucursales/bulk/status`,
        deleteSucursales: `${baseUrl}/sucursales/bulk/delete`,
    },
    usuarios: {
        getUsuarios: `${baseUrl}/users/all`,
        postUsuario: `${baseUrl}/users/create-user`,
        putUsuario: `${baseUrl}/users/`,
        deleteUsuario: `${baseUrl}/users/`,
        getUsuarioPorId: `${baseUrl}/users/`,
        me: `${baseUrl}/users/me`,
        login: `${baseUrl}/users/login`,
        register: `${baseUrl}/users/register`,
        cambiarContrasena: `${baseUrl}/users/cambiar-contrasena`,
        validateToken: `${baseUrl}/users/validate-token`,
        updateUserStatus: `${baseUrl}/users/`,
        bulkUpdateUserStatus: `${baseUrl}/users/bulk/status`,
        bulkDeleteUsers: `${baseUrl}/users/bulk/delete`,
    },
    empresas: {
        getEmpresas: `${baseUrl}/empresa/all`,
        getEmpresasPaginated: `${baseUrl}/empresa`,
        postEmpresa: `${baseUrl}/empresa`,
        putEmpresa: `${baseUrl}/empresa`,
        patchEmpresa: `${baseUrl}/empresa`,
        deleteEmpresa: `${baseUrl}/empresa`,
        getEmpresaPorId: `${baseUrl}/empresa`,
        deleteEmpresas: `${baseUrl}/empresa/bulk/delete`,
        updateMyCompany: `${baseUrl}/empresa/mi-empresa`,
    },
    correo: {
        sendMail: `${baseUrl}/mail-service/send`,
        verifyCode: `${baseUrl}/mail-service/verify`,
    },
    roles: {
        getRoles: `${baseUrl}/roles`,
        postRole: `${baseUrl}/roles`,
        putRole: `${baseUrl}/roles`,
        deleteRole: `${baseUrl}/roles`,
        getRolePorId: `${baseUrl}/roles`,
        getRolesByEmpresa: `${baseUrl}/roles/empresa`,
        bulkDeleteRoles: `${baseUrl}/roles/bulk/delete`,
        bulkUpdateStatus: `${baseUrl}/roles/bulk/status`,
    },
    permisos: {
        getPermisos: `${baseUrl}/permisos/all`,
        getPermisosByEmpresa: `${baseUrl}/permisos/empresa`,
    },
    ubicaciones: {
        provincias: `${baseUrl}/ubicaciones/provincias`,
        ciudadesByProvincia: `${baseUrl}/ubicaciones/ciudades`,
     },
    marcas: {
        getMarcas: `${baseUrl}/marcas`,
        postMarca: `${baseUrl}/marcas`,
        putMarca: `${baseUrl}/marcas`,
        deleteMarca: `${baseUrl}/marcas`,
        getMarcaPorId: `${baseUrl}/marcas`,
        getMarcasByEmpresa: `${baseUrl}/marcas/empresa`,
        bulkDeleteMarcas: `${baseUrl}/marcas/bulk/delete`,
        bulkUpdateStatus: `${baseUrl}/marcas/bulk/status`,
    },
    categorias: {
        getCategorias: `${baseUrl}/categorias`,
        getCategoriasByEmpresa: `${baseUrl}/categorias/empresa`,
        postCategoria: `${baseUrl}/categorias`,
        putCategoria: `${baseUrl}/categorias`,
        deleteCategoria: `${baseUrl}/categorias`,
        getCategoriaPorId: `${baseUrl}/categorias`,
        bulkDeleteCategorias: `${baseUrl}/categorias/bulk/delete`,
        bulkUpdateStatus: `${baseUrl}/categorias/bulk/status`,
    },
    productos: {
        getProductos: `${baseUrl}/productos`,
        postProducto: `${baseUrl}/productos`,
        putProducto: `${baseUrl}/productos`,
        deleteProducto: `${baseUrl}/productos`,
        getProductoPorId: `${baseUrl}/productos`,
        getProductosByEmpresa: `${baseUrl}/productos/empresa`,
        getProductosBySucursal: `${baseUrl}/productos/sucursal`,
        bulkDeleteProductos: `${baseUrl}/productos/bulk/delete`,
        bulkUpdateStatus: `${baseUrl}/productos/bulk/status`,
    },
    movimientosStock: {
        getMovimientosStock: `${baseUrl}/movimientos-stock`,
        getMovimientosByProducto: `${baseUrl}/movimientos-stock/producto`,
        ajusteStock: `${baseUrl}/movimientos-stock/ajuste-stock`,
    },
    unidadesMedida: {
        getUnidadMedida: `${baseUrl}/unidad-medida`,
        postUnidadMedida: `${baseUrl}/unidad-medida`,
        putUnidadMedida: `${baseUrl}/unidad-medida`,
        deleteUnidadMedida: `${baseUrl}/unidad-medida`,
        getUnidadMedidaPorId: `${baseUrl}/unidad-medida`,
        getUnidadesMedidaByEmpresa: `${baseUrl}/unidad-medida/empresa`,
        bulkDeleteUnidadesMedida: `${baseUrl}/unidad-medida/bulk/delete`,
        bulkUpdateStatus: `${baseUrl}/unidad-medida/bulk/status`,
    },
    contactos: {
        clientes: {
            getAll: `${baseUrl}/clientes/all`,
            post: `${baseUrl}/clientes`,
            put: `${baseUrl}/clientes`,
            patch: `${baseUrl}/clientes`,
            bulkStatus: `${baseUrl}/clientes/bulk/status`,
        },
        proveedores: {
            getAll: `${baseUrl}/proveedores/all`,
            post: `${baseUrl}/proveedores`,
            put: `${baseUrl}/proveedores`,
            patch: `${baseUrl}/proveedores`,
            bulkStatus: `${baseUrl}/proveedores/bulk/status`,
        },
    },
    ventas: {
        getVentas: `${baseUrl}/ventas`,
        getVentaPorId: `${baseUrl}/ventas`,
        getVentasBySucursal: `${baseUrl}/ventas/sucursal`,
        getVentasByEmpresa: `${baseUrl}/ventas/empresa`,
        postVenta: `${baseUrl}/ventas`,
        putVenta: `${baseUrl}/ventas`,
        deleteVenta: `${baseUrl}/ventas`,
        bulkDeleteVentas: `${baseUrl}/ventas/bulk/delete`,
    },
    listaPrecios: {
        getListaPrecios: `${baseUrl}/lista-precios`,
        postListaPrecios: `${baseUrl}/lista-precios`,
        putListaPrecios: `${baseUrl}/lista-precios`,
        deleteListaPrecios: `${baseUrl}/lista-precios`,
        getListaPreciosPorId: `${baseUrl}/lista-precios`,
        getListaPreciosByEmpresa: `${baseUrl}/lista-precios/empresa`,
        getProductosByListaPrecios: `${baseUrl}/lista-precios`,
        bulkDeleteListaPrecios: `${baseUrl}/lista-precios/bulk/delete`,
        bulkUpdateStatus: `${baseUrl}/lista-precios/bulk/status`,
    },
    compras : {
        getCompras: `${baseUrl}/compras`,
        getCompraPorId: `${baseUrl}/compras`,
        getComprasBySucursal: `${baseUrl}/compras/sucursal`,
        getComprasByEmpresa: `${baseUrl}/compras/empresa`,
        postCompra: `${baseUrl}/compras`,
        putCompra: `${baseUrl}/compras`,
        deleteCompra: `${baseUrl}/compras`,
        bulkDeleteCompras: `${baseUrl}/compras/bulk/delete`,
        asociarPago: `${baseUrl}/compras`,
    }
};
